"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const attendance_1 = require("../controllers/attendance");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.use(middlewares_1.middleware.allowAppRoles('user', 'admin'));
router.use(middlewares_1.middleware.allowMembershipRoles('employee', 'company'));
router.get('/', attendance_1.attendanceController.findAllAttendance);
router.get('/detail/:attendanceId', attendance_1.attendanceController.findDetailAttendance);
router.get('/last-status/:userId', attendance_1.attendanceController.findLastStatus);
router.get('/last-status/detail/:scheduleId', attendance_1.attendanceController.findDetailLastStatusAttendance);
router.post('/', attendance_1.attendanceController.createAttendance);
router.get('/histories', attendance_1.attendanceController.findAllAttendanceHistories);
router.get('/histories/detail/:attendanceHistoryId', attendance_1.attendanceController.findDetailAttendanceHistory);
exports.default = router;
