"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const company_1 = require("../controllers/company");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.use(middlewares_1.middleware.allowAppRoles('admin', 'superAdmin'));
router.get('/', company_1.companyControllers.findAll);
router.get('/detail/', middlewares_1.middleware.allowMembershipRoles('company'), company_1.companyControllers.findDetail);
router.patch('/', middlewares_1.middleware.allowMembershipRoles('company'), company_1.companyControllers.update);
exports.default = router;
