"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const appCheck_routes_1 = __importDefault(require("./appCheck.routes"));
const schedule_routes_1 = __importDefault(require("./schedule.routes"));
const employee_routes_1 = __importDefault(require("./employee.routes"));
const auth_routes_1 = __importDefault(require("./auth.routes"));
const attendance_routes_1 = __importDefault(require("./attendance.routes"));
const statistic_routes_1 = __importDefault(require("./statistic.routes"));
const myProfile_routes_1 = __importDefault(require("./myProfile.routes"));
const otp_routes_1 = __importDefault(require("./otp.routes"));
const office_routes_1 = __importDefault(require("./office.routes"));
const company_routes_1 = __importDefault(require("./company.routes"));
const membership_routes_1 = __importDefault(require("./membership.routes"));
const appInfo_routes_1 = __importDefault(require("./appInfo.routes"));
const position_routes_1 = __importDefault(require("./position.routes"));
const report_routes_1 = __importDefault(require("./report.routes"));
const faceRecognition_routes_1 = __importDefault(require("./faceRecognition.routes"));
const breakTime_routes_1 = __importDefault(require("./breakTime.routes"));
const admin_routes_1 = __importDefault(require("./admin.routes"));
const scheduler_routes_1 = __importDefault(require("./scheduler.routes"));
const apiVersion = '/api/v1';
const appRouterV1 = (app) => {
    app.use(apiVersion, appCheck_routes_1.default);
    app.use(apiVersion + '/info', appInfo_routes_1.default);
    app.use(apiVersion + '/employees', employee_routes_1.default);
    app.use(apiVersion + '/auth', auth_routes_1.default);
    app.use(apiVersion + '/offices', office_routes_1.default);
    app.use(apiVersion + '/schedules', schedule_routes_1.default);
    app.use(apiVersion + '/attendances', attendance_routes_1.default);
    app.use(apiVersion + '/companies', company_routes_1.default);
    app.use(apiVersion + '/statistic', statistic_routes_1.default);
    app.use(apiVersion + '/my-profiles', myProfile_routes_1.default);
    app.use(apiVersion + '/otp', otp_routes_1.default);
    app.use(apiVersion + '/memberships', membership_routes_1.default);
    app.use(apiVersion + '/positions', position_routes_1.default);
    app.use(apiVersion + '/reports', report_routes_1.default);
    app.use(apiVersion + '/face-recognitions', faceRecognition_routes_1.default);
    app.use(apiVersion + '/break-times', breakTime_routes_1.default);
    app.use(apiVersion + '/admin', admin_routes_1.default);
    app.use(apiVersion + '/scheduler-runs', scheduler_routes_1.default);
};
exports.appRouterV1 = appRouterV1;
