"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const membership_1 = require("../controllers/membership");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.get('/', middlewares_1.middleware.allowAppRoles('user', 'admin'), middlewares_1.middleware.allowMembershipRoles('employee', 'company'), membership_1.membershipControllers.findAll);
router.post('/invite', middlewares_1.middleware.allowAppRoles('user'), membership_1.membershipControllers.invite);
router.patch('/', middlewares_1.middleware.allowAppRoles('admin'), middlewares_1.middleware.allowMembershipRoles('company'), membership_1.membershipControllers.update);
router.delete('/:membershipId', middlewares_1.middleware.allowAppRoles('user', 'admin'), middlewares_1.middleware.allowMembershipRoles('employee', 'company'), membership_1.membershipControllers.remove);
exports.default = router;
