"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../middlewares");
const myProfile_1 = require("../controllers/myProfile");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.get('/', myProfile_1.myProfileController.find);
router.patch('/', middlewares_1.middleware.useAuthorization, myProfile_1.myProfileController.update);
router.patch('/onboardings', middlewares_1.middleware.useAuthorization, middlewares_1.middleware.allowAppRoles('admin'), myProfile_1.myProfileController.updateOnboardingStatus);
exports.default = router;
