"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const statistic_1 = require("../controllers/statistic");
const middlewares_1 = require("../middlewares");
const router = (0, express_1.Router)();
router.use(middlewares_1.middleware.useAuthorization);
router.get('/total', middlewares_1.middleware.allowAppRoles('admin'), middlewares_1.middleware.allowMembershipRoles('company'), statistic_1.statisticController.findTotal);
router.get('/productivities', middlewares_1.middleware.allowAppRoles('user', 'admin'), middlewares_1.middleware.allowMembershipRoles('employee', 'company'), statistic_1.statisticController.productivities);
exports.default = router;
